name: Client

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Client-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build, and test
        env:
          VITE_API_URL: ${{ secrets.SERVER_URL }}
        run: |
          cd packages/client
          npm install
          npm run build
          npm test

      - name: Install JQ and get version from packages.json into env variable
        run: |
          sudo apt-get install jq
          echo "CLIENT_VERSION=$(jq -r '.version' packages/client/package.json)" >> $GITHUB_ENV

      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/client:${{ env.CLIENT_VERSION }}-${{ github.sha }} .
          docker push ${{ secrets.ACR_REGISTRY }}/client:${{ env.CLIENT_VERSION }}-${{ github.sha }}