name: Client

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'packages/client/**'
      - '.github/workflows/client.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Client-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JQ and get version from packages.json into env variable
        run: |
          sudo apt-get install jq
          echo "CLIENT_VERSION=$(jq -r '.version' packages/client/package.json)" >> $GITHUB_ENV


      - name: Package client and save as GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: client-${{ env.CLIENT_VERSION }}-${{ github.run_number }}-${{ github.sha }}
          path: packages/client/dist

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            cd packages/client
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/client:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/client:latest

      - name: 'Deploy container app'
        run: |
          az containerapp update \
              --subscription ${{ secrets.SUBSCRIPTION_ID }}
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --name  ${{ secrets.CLIENT_CONTAINER_APP_NAME }} \
              --image  ${{ secrets.REGISTRY_LOGIN_SERVER }}/client:latest