name: Server

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: 
      - '*'
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: server-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JQ and get version from packages.json into env variable
        run: |
          sudo apt-get install jq
          echo "CLIENT_VERSION=$(jq -r '.version' packages/client/package.json)" >> $GITHUB_ENV

      - name: Install, build, and test
        run: |
          cd packages/server
          npm install
          npm run build
          npm test

      - name: Package server and save as GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-${{ env.CLIENT_VERSION }}-${{ github.sha }}
          path: packages/server

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            cd packages/server
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:${{ env.CLIENT_VERSION }}-${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:${{ env.CLIENT_VERSION }}-${{ github.sha }}
