name: Server

on:

  push:
    branches: 
      - 'main'

    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: server-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install JQ and get version from packages.json into env variable
        run: |
          sudo apt-get install jq
          echo "SERVER_VERSION=$(jq -r '.version' packages/server/package.json)" >> $GITHUB_ENV



      - name: Package server and save as GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: server-${{ env.SERVER_VERSION }}-${{ github.run_number }}-${{ github.sha }}
          path: packages/server

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            cd packages/server
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:${{ env.SERVER_VERSION }}-${{ github.run_number }}-${{ github.sha }}
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:${{ env.SERVER_VERSION }}-${{ github.run_number }}-${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest

      - name: 'Set secrets for container app'
        run: |
          az containerapp secret set \
              --subscription ${{ secrets.SUBSCRIPTION_ID }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --name  ${{ secrets.SERVER_CONTAINER_APP_NAME }} --secrets "database-url=${{ secrets.DATABASE_URL }}" "database-name=${{ secrets.DATABASE_NAME }}"    

      - name: 'Deploy container app'
        run: |
          az containerapp update \
              --subscription ${{ secrets.SUBSCRIPTION_ID }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --name  ${{ secrets.SERVER_CONTAINER_APP_NAME }} \
              --image  ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest 

