name: Server

on:
  workflow_dispatch:
  push:
    branches: 
      - '*'
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: 
      - 'main'
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: server-Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build, and test
        run: |
          cd packages/server
          npm install
          npm run build
          npm test

      - name: Install JQ and get version from packages.json into env variable
        run: |
          sudo apt-get install jq
          echo "server_VERSION=$(jq -r '.version' packages/server/package.json)" >> $GITHUB_ENV

      - name: Docker Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/server:${{ env.server_VERSION }}-${{ github.sha }} .
          docker push ${{ secrets.ACR_REGISTRY }}/server:${{ env.server_VERSION }}-${{ github.sha }}